### ISSUE TITLE
change how the game deals with double guesses of the same letter

### ISSUE THREAD

**Issue by approachcircle** [jamieabw/Hangman#1]
# issue
at the moment, if you guess the same letter twice the game just restarts and you lose all progress of that round, which is probably not the best way to handle that.
# solution
state that the guessed letter has already been guessed, and ensure that it does not contribute to the number of lives a player has left, and that it is not added to the list of already guessed characters again.

**Comment by jamieabw** [comment]
Fixed - no longer restarts and instead goes through the while loop once again without deducting any lives and warns the user of inputting a duplicate or invalid string
